### ISSUE TITLE
[Bug]: The clientNum type should be of an atomic type.

### ISSUE THREAD

**Issue by namewxt1220** [oceanbase/modis#3]
https://github.com/oceanbase/modis/blob/410c13b60d5d795923eaddd0c08ea1d2b003da1e/connection/server/server.go#L135-L145
The accept event should increment by 1, and the connection close event should decrement by 1.

**Comment by lyxiong0** [comment]
Thanks for finding the Modis issue. We have fixed it in the commit below:
[0965dd2f2a9d491e30c949f5648854d53cdfcb94](https://github.com/oceanbase/modis/commit/0965dd2f2a9d491e30c949f5648854d53cdfcb94)

In this commit, `ClientNum` is set to an atomic variable and -1 on disconnection.
